hw11
speysinger/JavaSIS-3.20 pull request #21
Opened 2020-04-23 18:27 UTC by speysinger

Не придумал способа как с помощью пагинации в бд нормально за 1 запрос получить отфильтрованный запрос с количеством элементов под страницу, сохранив при этом ещё и количество файлов после фильтрации. При использовании сервисов или репозиториев в тесте вываливается Nullpointerexception, не совсем понял почему.

2020-04-27 03:05 UTC, Bael requested changes
Просьба исправить логику подсчета баллов

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/data/Selected_AnswerRepository.java
> +public interface Selected_AnswerRepository extends CrudRepository<Selected_Answer, Long> {
underscore не приветствуется

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/data/QuestionRepository.java
>          extends CrudRepository<Question, Long> {
для работы с пагинацией мы рассматривали на занятии по спринг дата PagingAndSortingRepository<T,ID>

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/entity/Selected_Answer.java
> +public class Selected_Answer extends BaseEntity {
underscore не приветствуется, имена классов пишем в паскаль кейсе

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/entity/Session.java
> +    Date date;
LocalDate

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/JournalServiceImpl.java
> +                for (JournalFilterItem journalFilterItem : filterItems) {
не лучше ли фильтрацию проводить на этапе выборки?

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +                    subList(0, listSize / 2).
если пишите такую логику нужны пояснения в комментариях зачем

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +                sum() / answeredQuestionDTOS.size()) * 100;
answeredQuestionDTOS.size() может быть равным нулю?

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +        if (correctAnswersCount == 1 && userWrongAnswersCount == 0) {
проще if (correctAnswersCount == 1) { return userWrongAnswersCount == 0 }
еще не вижу как у вас учтена ситуация когда человек не выбрал ни одного варианта, userWrongAnswersCount  будет равен 0 и баллы засчитаются (в случае одного правильного ответа).

2020-04-27 03:05 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +                    answer.setId(Long.parseLong(sessionQuestionAnswer.getId()));
проще у дто сделать тип id long

2020-04-27 14:54 UTC, speysinger commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/JournalServiceImpl.java
> +                for (JournalFilterItem journalFilterItem : filterItems) {
> не лучше ли фильтрацию проводить на этапе выборки?

У меня проблема в том, что не получается совместить пагинацию в бд и фильтрацию по, например, количеству ответов. Хотел исходя из переданных фильтров формировать sql запрос, передавать как параметр и выполнять его, но похоже так нельзя. Думал про способ со спецификациями, но не понял как обратиться к другой таблице (для посчёта количества возможных ответов на вопрос).

2020-04-28 02:27 UTC, Bael requested changes
все таки поправьте пожалуйста деление на ноль при подсчете количества баллов

2020-04-28 02:27 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +                            (answersCount - correctAnswersCount));
если все варианты ответов верные - здесь мы получим 0
нужно обработать этот вариант отдельно.

2020-04-28 02:27 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/session/impl/SessionServiceImpl.java
> +            return (userWrongAnswersCount == 0 && userCorrectAnswersCount == 1) ? 1 : 0;
здесь поправили, вижу

2020-04-28 05:54 UTC, Bael requested changes
Пожалуйста, поправьте этот кусок
      return Math.max(0, userCorrectAnswersCount / correctAnswersCount -
                    userWrongAnswersCount /
                            (answersCount - correctAnswersCount));

не будет обработана ситуация когда все варианты ответов - верные

2020-04-28 05:54 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/JournalServiceImpl.java
> +                for (JournalFilterItem journalFilterItem : filterItems) {
Вам нужно репозиторий расширить интерфейсом JpaSpecificationExecutor<T>, там есть метод findAll принимающий на вход спецификацию и PageRequest

2020-04-28 05:54 UTC, Bael commented on unit-11/app-server/src/main/java/com/github/siberianintegrationsystems/restApp/service/journal/JournalServiceImpl.java
> +                for (JournalFilterItem journalFilterItem : filterItems) {
спецификации не годятся в одном случае - если вам нужно сделать джойн со стороны one таблицы

2020-04-28 08:23 UTC, Bael approved these changes
принято!

2020-09-30 05:37 UTC, merged